### ISSUE TITLE
ValueError: too many values to unpack in km.py script

### ISSUE THREAD

**Issue by julgrandvallet** [j-rehn/RaScALL#2]
## I am encountering a "ValueError: too many values to unpack" error when running RaScALL.

**To reproduce**

I ran the following command:

```
bash run_km.sh CA2086_R1.fastq.gz CA2086_R2.fastq.gz 12 ALL_targets/IGH_fusion/
```

**My Environment**

OS: **Linux pop-os 6.2.6-76060206-generic #202303130630~1681329778~22.04~d824cd4 SMP PREEMPT_DYNAMIC Wed A x86_64 x86_64 x86_64 GNU/Linux**
Python version: **3.7.10**

**Additional context**

```
Traceback (most recent call last):
  File "/home/juliangc/RaScALL/.virtualenvs/km/bin/km", line 8, in <module>
    sys.exit(main())
  File "/home/juliangc/RaScALL/.virtualenvs/km/lib/python3.7/site-packages/km/km.py", line 67, in main
    args.func(args, parser)
  File "/home/juliangc/RaScALL/.virtualenvs/km/lib/python3.7/site-packages/km/tools/find_mutation.py", line 41, in main_find_mut
    ref_seqs, ref_attr = uc.file_2_seq(seq_f)
  File "/home/juliangc/RaScALL/.virtualenvs/km/lib/python3.7/site-packages/km/utils/common.py", line 41, in file_2_seq
    k, v = x.split("=")
ValueError: too many values to unpack (expected 2)

```

I have followed the instructions provided in the README.md file of the RaScALL repository and believe that I am running the script correctly. It happens with all the directories inside **ALL_targets/**

**Comment by jimmybgammyknee** [comment]
Thanks for finding this bug @julgrandvallet . Looks to be the new version of km-walk which breaks some of the argparse code. Ive edited the repo and sent a pull request #3 to @j-rehn . _Hopefully_ this fixes the issue

**Comment by julgrandvallet** [comment]
Thank you very much. Should I install all again?, I removed RaScALL and cloned the repository again but I am getting this (again I think?):
```
(RaScALL) juliangc@pop-os:~/RaScALL$ bash run_km.sh /home/juliangc/Videos/copy_results/fastq/CA2086_R1.fastq.gz /home/juliangc/Videos/copy_results/fastq/CA2086_R2.fastq.gz 8 ALL_targets/focal_deletions/
Jellyfish Sample file exists
525416 /home/juliangc/RaScALL/output/CA2086/CA2086_countTable31.jf
Traceback (most recent call last):
  File "/home/juliangc/RaScALL/.virtualenvs/km/bin/km", line 8, in <module>
    sys.exit(main())
  File "/home/juliangc/RaScALL/.virtualenvs/km/lib/python3.7/site-packages/km/km.py", line 67, in main
    args.func(args, parser)
  File "/home/juliangc/RaScALL/.virtualenvs/km/lib/python3.7/site-packages/km/tools/find_mutation.py", line 41, in main_find_mut
    ref_seqs, ref_attr = uc.file_2_seq(seq_f)
  File "/home/juliangc/RaScALL/.virtualenvs/km/lib/python3.7/site-packages/km/utils/common.py", line 41, in file_2_seq
    k, v = x.split("=")
ValueError: too many values to unpack (expected 2)
```

**Comment by jimmybgammyknee** [comment]
You'll need to completely remove everything (conda/directory etc). Looks like you're still using the old version

**Comment by julgrandvallet** [comment]
Thank you very much for you help, it worked out perfectly now.
